# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PlotWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotWindow(object):
    def setupUi(self, PlotWindow):
        PlotWindow.setObjectName("PlotWindow")
        PlotWindow.resize(520, 321)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlotWindow.sizePolicy().hasHeightForWidth())
        PlotWindow.setSizePolicy(sizePolicy)
        PlotWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        PlotWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(PlotWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_plot = QtWidgets.QLabel(self.centralwidget)
        self.lbl_plot.setGeometry(QtCore.QRect(10, 10, 500, 300))
        self.lbl_plot.setAutoFillBackground(True)
        self.lbl_plot.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_plot.setLineWidth(1)
        self.lbl_plot.setText("")
        self.lbl_plot.setScaledContents(True)
        self.lbl_plot.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_plot.setObjectName("lbl_plot")
        PlotWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PlotWindow)
        QtCore.QMetaObject.connectSlotsByName(PlotWindow)

    def retranslateUi(self, PlotWindow):
        _translate = QtCore.QCoreApplication.translate
        PlotWindow.setWindowTitle(_translate("PlotWindow", "Plot"))
